// Heite Stavrim - Kategoriliste
// Nynorsk og engelsk oversettelse

const CATEGORIES = {
    nn: [
        "Jentenamn",
        "Gutenamn",
        "Hovudstader",
        "Land",
        "Dyr",
        "Musikkinstrument",
        "Blomar",
        "Edelsteinar",
        "Teikneseriefigurar",
        "Ord på fire bokstavar",
        "Merkevarer",
        "Ting på ei strand",
        "Nettstader",
        "Bilmerke",
        "Ting som er klissete",
        "Ting ein roper",
        "Dårlege årsakar til å vere for sein",
        "Ting som irriterer deg",
        "Iskremsmakar",
        "Steikt mat",
        "Elv",
        "Halloweendrakter",
        "Stader å dra på date",
        "Kallenamn",
        "Jobbtitlar",
        "Namn som passar til gut og jente",
        "Språk",
        "Historiske personar",
        "Kjendisar",
        "Høgtider",
        "Ting i ein suvenirbutikk",
        "Ting på eit kart",
        "Slektningar",
        "Ting på eit kontor",
        "Programvare",
        "Noko du er redd for",
        "Appar",
        "Elektroniske einingar",
        "Filmtitlar",
        "Boktitlar",
        "Kjæledyr",
        "Musikkinstrument",
        "Musikksjangrar",
        "Dyr som bur i vatn",
        "Dyr i dyrehagen",
        "Ting ein får i posten",
        "Songtittel",
        "Feriedestinasjonar",
        "Kjende dyr",
        "Drikkar",
        "Hobbyar",
        "Ting i verdsrommet",
        "Sjokoladetypar",
        "Måtar å reise frå A til B på",
        "Møblar",
        "Plantar",
        "Ting i eit museum",
        "Idrettslag",
        "Ekstremidrettar",
        "Fargar",
        "Verktøy",
        "Farlege aktivitetar",
        "Ting ein kan gå viralt for",
        "Gjenstand innanfor synsrekkevidde",
        "Ting som er blå",
        "Kroppsdelar",
        "Dyre ting",
        "Snacks",
        "Sunn mat",
        "Noko folk hatar å gjere",
        "Noko som overrasker deg",
        "Noko overnaturleg",
        "Noko å strebe etter",
        "Prisar/seremoniar",
        "Årsaker til å miste jobben",
        "Firebokstavsord (på eit fremmed språk)",
        "TV-seriar",
        "Brotsverk",
        "Kontorrekvisita",
        "Ting på rommet ditt",
        "Ting knytt til jul",
        "Reality-TV show",
        "Brettspel",
        "Videospel",
        "Superheltar",
        "Pizzafyll",
        "Asiatisk mat",
        "Ting som får deg til å le",
        "Noko du held hemmeleg",
        "Ting ein seier på jobb",
        "Mytiske skapningar",
        "Voksenaktivitetar",
        "Emne du likar å snakke om",
        "Frokostmat",
        "Irriterande klisje",
        "Ting ein ser på ein biltur",
        "Ting ein ser i nyheitene",
        "Ting ein finn i naturen",
        "Ting i som du ikkje ønskje å plukke opp frå bakken",
        "Ting på folkets bucket list",
        "Ting på ein flyplass",
        "Skurkar",
        "Tal",
        "Ord med to tydingar",
        "Gode eigenskapar for ein ven",
        "Gode grunnar til å ikkje gå på skulen",
        "Klede",
        "Ord knytt til sjølvpleie",
        "Kunstprosjekt",
        "Vêrfenomen",
        "Ting knytt til sumar",
        "Musikalar",
        "Ting du ser fram til",
        "Presidentar"
    ],
    en: [
        "A girl's name",
        "A boy's name",
        "Capital cities",
        "Countries",
        "Animals",
        "Musical Instruments",
        "Flowers",
        "Gemstones",
        "Cartoon Characters",
        "Four letter words",
        "Brands",
        "Things on a beach",
        "Websites",
        "Cars",
        "Things that are sticky",
        "Things that you shout",
        "Excuses for being late",
        "Pet peeves",
        "Ice cream flavors",
        "Fried foods",
        "Bodies of water",
        "Halloween costumes",
        "Places to go on a date",
        "Nicknames",
        "Job titles",
        "College majors",
        "Languages",
        "Historical figures",
        "Celebrities",
        "Holidays",
        "Items in a gift shop",
        "Things on a map",
        "Relatives",
        "Things in an office",
        "Software",
        "Fears",
        "Apps",
        "Electronic devices",
        "Movie titles",
        "Book titles",
        "Pets",
        "Musical instruments",
        "Types of music",
        "Aquatic animals",
        "Animals in a zoo",
        "Things you get in the mail",
        "Song title",
        "Vacation destination",
        "Famous animals",
        "Drinks",
        "Hobbies",
        "Things in space",
        "Types of candy",
        "Ways to get from here to there",
        "Furniture",
        "Plants",
        "Things in a museum",
        "Sports teams",
        "Extreme sports",
        "Colors",
        "Tools",
        "Dangerous activities",
        "Things you might go viral for",
        "Item within eyesight",
        "Things that are blue",
        "Body parts",
        "Expensive items",
        "Snack foods",
        "Healthy foods",
        "Animals in a zoo",
        "Something people hate doing",
        "Something that surprises you",
        "A common lie",
        "Something to strive for",
        "Awards/ceremonies",
        "Fireable offenses",
        "Random acts of kindness",
        "Four letter word (in a foreign language)",
        "TV shows",
        "Crimes",
        "Office supplies",
        "Things on your work desk",
        "Things associated with Xmas",
        "Game shows",
        "Board games",
        "Video games",
        "Superheroes",
        "Pizza toppings",
        "World cuisine",
        "Things that make you laugh",
        "Something you keep secret",
        "Things you say at work",
        "Mythical creatures",
        "\"Adulting\" activities",
        "Topics you like to talk about",
        "Breakfast foods",
        "Annoying movie tropes",
        "Things you see on a road trip",
        "Things you see in the news",
        "Things you find in nature",
        "Things in the sky",
        "Things on people's bucket lists",
        "Things in an airport",
        "Villains",
        "Four syllable words",
        "Words with two meanings",
        "Good qualities for a friend",
        "Guilty pleasures",
        "Clothing",
        "Words associated with self-care",
        "Art projects",
        "Weather",
        "Things associated with summer",
        "Musicals",
        "Things you look forward to",
        "Presidents"
    ],
    custom: []
};
