/* ══════════════════════════════════════════════
   LISTE.JS — Den innebygde innspelingslista

   Hovudlista er generert frå `ljodstigen/INNSPELING.md`. Steg 6 er ei
   planlagd utviding frå `ljodstigen/VIDARE_PROGRESJON.md`; han skal ikkje
   inn i den publiserte lydbanken før spelet kan handsame fleire bokstavar
   som éin grafemlyd.

   Ei liste har fire felt: `id` (blir mappenamn og filnamn-prefiks),
   `name`, `note` og `banks`. Kvar bank blir ei mappe i zip-fila, og
   kvart klipp ei fil som heiter `<id>.mp3` eller `<id>.wav`.
   ══════════════════════════════════════════════ */
window.LB = window.LB || {};

LB.builtinList = {
  app: 'ljodbanken',
  version: 1,
  id: "ljodstigen",
  name: "Ljodstigen",
  note: "Same stemme, same mikrofon og same rom for heile settet. Snakk roleg og vanleg — ikkje overtydeleg barnestemme. Steg 6 er planlagde opptak for ei seinare utviding av Ljodstigen.",
  banks: [
    {
      id: "fonem",
      name: "Bokstavlydar",
      note: "Det viktigaste settet, og det einaste der uttalen er kritisk. Ingen schwa-hale: /m/ skal vere ein hald m-lyd, ikkje «mø».",
      items: [
        { id: "f_a", label: "a", tag: "vokal", hint: "Hald 0,5–0,7 s. Rein vokal, ikkje dra mot ein diftong." },
        { id: "f_e", label: "e", tag: "vokal", hint: "Hald 0,5–0,7 s. Rein vokal, ikkje dra mot ein diftong." },
        { id: "f_l", label: "l", tag: "haldlyd", hint: "Hald 0,6–0,8 s. INGEN vokal på slutten." },
        { id: "f_m", label: "m", tag: "haldlyd", hint: "Hald 0,6–0,8 s. INGEN vokal på slutten." },
        { id: "f_o", label: "o", tag: "vokal", hint: "Hald 0,5–0,7 s. Rein vokal, ikkje dra mot ein diftong." },
        { id: "f_r", label: "r", tag: "haldlyd", hint: "Hald 0,6–0,8 s. INGEN vokal på slutten." },
        { id: "f_s", label: "s", tag: "haldlyd", hint: "Hald 0,6–0,8 s. INGEN vokal på slutten." },
        { id: "f_i", label: "i", tag: "vokal", hint: "Hald 0,5–0,7 s. Rein vokal, ikkje dra mot ein diftong." },
        { id: "f_k", label: "k", tag: "lukkelyd", hint: "Så kort som råd. Ikkje «be» eller «bø» — berre sjølve smellen." },
        { id: "f_n", label: "n", tag: "haldlyd", hint: "Hald 0,6–0,8 s. INGEN vokal på slutten." },
        { id: "f_t", label: "t", tag: "lukkelyd", hint: "Så kort som råd. Ikkje «be» eller «bø» — berre sjølve smellen." },
        { id: "f_v", label: "v", tag: "haldlyd", hint: "Hald 0,6–0,8 s. INGEN vokal på slutten." },
        { id: "f_d", label: "d", tag: "lukkelyd", hint: "Så kort som råd. Ikkje «be» eller «bø» — berre sjølve smellen." },
        { id: "f_f", label: "f", tag: "haldlyd", hint: "Hald 0,6–0,8 s. INGEN vokal på slutten." },
        { id: "f_g", label: "g", tag: "lukkelyd", hint: "Så kort som råd. Ikkje «be» eller «bø» — berre sjølve smellen." },
        { id: "f_u", label: "u", tag: "vokal", hint: "Hald 0,5–0,7 s. Rein vokal, ikkje dra mot ein diftong." },
        { id: "f_å", label: "å", tag: "vokal", hint: "Hald 0,5–0,7 s. Rein vokal, ikkje dra mot ein diftong." },
        { id: "f_b", label: "b", tag: "lukkelyd", hint: "Så kort som råd. Ikkje «be» eller «bø» — berre sjølve smellen." },
        { id: "f_h", label: "h", tag: "haldlyd", hint: "Hald 0,6–0,8 s. INGEN vokal på slutten." },
        { id: "f_p", label: "p", tag: "lukkelyd", hint: "Så kort som råd. Ikkje «be» eller «bø» — berre sjølve smellen." },
        { id: "f_y", label: "y", tag: "vokal", hint: "Hald 0,5–0,7 s. Rein vokal, ikkje dra mot ein diftong." },
        { id: "f_ø", label: "ø", tag: "vokal", hint: "Hald 0,5–0,7 s. Rein vokal, ikkje dra mot ein diftong." },
        { id: "f_c", label: "c", tag: "haldlyd", hint: "Hald 0,6–0,8 s. INGEN vokal på slutten." },
        { id: "f_j", label: "j", tag: "haldlyd", hint: "Hald 0,6–0,8 s. INGEN vokal på slutten." },
        { id: "f_q", label: "q", tag: "haldlyd", hint: "Hald 0,6–0,8 s. INGEN vokal på slutten." },
        { id: "f_w", label: "w", tag: "haldlyd", hint: "Hald 0,6–0,8 s. INGEN vokal på slutten." },
        { id: "f_x", label: "x", tag: "haldlyd", hint: "Hald 0,6–0,8 s. INGEN vokal på slutten." },
        { id: "f_z", label: "z", tag: "haldlyd", hint: "Hald 0,6–0,8 s. INGEN vokal på slutten." },
        { id: "f_æ", label: "æ", tag: "vokal", hint: "Hald 0,5–0,7 s. Rein vokal, ikkje dra mot ein diftong." },
      ]
    },
    {
      id: "namn",
      name: "Bokstavnamn",
      note: "Slik bokstaven heiter, ikkje lyden han lagar.",
      items: [
        { id: "n_a", label: "a", tag: "bokstavnamn", hint: "Du seier «a» — namnet på bokstaven, ikkje lyden." },
        { id: "n_e", label: "e", tag: "bokstavnamn", hint: "Du seier «e» — namnet på bokstaven, ikkje lyden." },
        { id: "n_l", label: "l", tag: "bokstavnamn", hint: "Du seier «ell» — namnet på bokstaven, ikkje lyden." },
        { id: "n_m", label: "m", tag: "bokstavnamn", hint: "Du seier «emm» — namnet på bokstaven, ikkje lyden." },
        { id: "n_o", label: "o", tag: "bokstavnamn", hint: "Du seier «o» — namnet på bokstaven, ikkje lyden." },
        { id: "n_r", label: "r", tag: "bokstavnamn", hint: "Du seier «err» — namnet på bokstaven, ikkje lyden." },
        { id: "n_s", label: "s", tag: "bokstavnamn", hint: "Du seier «ess» — namnet på bokstaven, ikkje lyden." },
        { id: "n_i", label: "i", tag: "bokstavnamn", hint: "Du seier «i» — namnet på bokstaven, ikkje lyden." },
        { id: "n_k", label: "k", tag: "bokstavnamn", hint: "Du seier «kå» — namnet på bokstaven, ikkje lyden." },
        { id: "n_n", label: "n", tag: "bokstavnamn", hint: "Du seier «enn» — namnet på bokstaven, ikkje lyden." },
        { id: "n_t", label: "t", tag: "bokstavnamn", hint: "Du seier «te» — namnet på bokstaven, ikkje lyden." },
        { id: "n_v", label: "v", tag: "bokstavnamn", hint: "Du seier «ve» — namnet på bokstaven, ikkje lyden." },
        { id: "n_d", label: "d", tag: "bokstavnamn", hint: "Du seier «de» — namnet på bokstaven, ikkje lyden." },
        { id: "n_f", label: "f", tag: "bokstavnamn", hint: "Du seier «eff» — namnet på bokstaven, ikkje lyden." },
        { id: "n_g", label: "g", tag: "bokstavnamn", hint: "Du seier «ge» — namnet på bokstaven, ikkje lyden." },
        { id: "n_u", label: "u", tag: "bokstavnamn", hint: "Du seier «u» — namnet på bokstaven, ikkje lyden." },
        { id: "n_å", label: "å", tag: "bokstavnamn", hint: "Du seier «å» — namnet på bokstaven, ikkje lyden." },
        { id: "n_b", label: "b", tag: "bokstavnamn", hint: "Du seier «be» — namnet på bokstaven, ikkje lyden." },
        { id: "n_h", label: "h", tag: "bokstavnamn", hint: "Du seier «hå» — namnet på bokstaven, ikkje lyden." },
        { id: "n_p", label: "p", tag: "bokstavnamn", hint: "Du seier «pe» — namnet på bokstaven, ikkje lyden." },
        { id: "n_y", label: "y", tag: "bokstavnamn", hint: "Du seier «y» — namnet på bokstaven, ikkje lyden." },
        { id: "n_ø", label: "ø", tag: "bokstavnamn", hint: "Du seier «ø» — namnet på bokstaven, ikkje lyden." },
        { id: "n_c", label: "c", tag: "bokstavnamn", hint: "Du seier «se» — namnet på bokstaven, ikkje lyden." },
        { id: "n_j", label: "j", tag: "bokstavnamn", hint: "Du seier «je» — namnet på bokstaven, ikkje lyden." },
        { id: "n_q", label: "q", tag: "bokstavnamn", hint: "Du seier «ku» — namnet på bokstaven, ikkje lyden." },
        { id: "n_w", label: "w", tag: "bokstavnamn", hint: "Du seier «dobbel-ve» — namnet på bokstaven, ikkje lyden." },
        { id: "n_x", label: "x", tag: "bokstavnamn", hint: "Du seier «eks» — namnet på bokstaven, ikkje lyden." },
        { id: "n_z", label: "z", tag: "bokstavnamn", hint: "Du seier «sett» — namnet på bokstaven, ikkje lyden." },
        { id: "n_æ", label: "æ", tag: "bokstavnamn", hint: "Du seier «æ» — namnet på bokstaven, ikkje lyden." },
      ]
    },
    {
      id: "digrafar",
      name: "Nye lydgrupper — steg 6",
      note: "Planlagde opptak til neste steg. «ng» er to bokstavar som står for éin språklyd. Ikkje spel inn bokstavnamna eller legg til ein vokal.",
      items: [
        { id: "f_ng", label: "/ŋ/ — ng", tag: "steg 6 · lydgruppe", hint: "Hald den mjuke naselyden /ŋ/ i 0,6–0,8 s, som på slutten av «ring». Ingen vokal før eller etter." },
      ]
    },
    {
      id: "ord",
      name: "Ord",
      note: "Les ordet naturleg og heilt. Appen lyder sjølv ordet ved å spele fonema etter kvarandre; dette klippet er fasiten eleven skal kjenne att.",
      items: [
        { id: "o_sol", label: "sol", tag: "steg 1", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava. NB: o = annan lyd." },
        { id: "o_mor", label: "mor", tag: "steg 1", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava. NB: o = annan lyd." },
        { id: "o_ler", label: "ler", tag: "steg 1", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_sal", label: "sal", tag: "steg 1", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_mas", label: "mas", tag: "steg 1", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_ras", label: "ras", tag: "steg 1", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_lam", label: "lam", tag: "steg 1", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_mel", label: "mel", tag: "steg 1", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_sel", label: "sel", tag: "steg 1", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_rom", label: "rom", tag: "steg 1", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava. NB: o = annan lyd." },
        { id: "o_ros", label: "ros", tag: "steg 1", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava. NB: o = annan lyd." },
        { id: "o_rose", label: "rose", tag: "steg 1", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_mose", label: "mose", tag: "steg 1", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_is", label: "is", tag: "steg 2", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_ti", label: "ti", tag: "steg 2", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_til", label: "til", tag: "steg 2", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_vin", label: "vin", tag: "steg 2", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_vil", label: "vil", tag: "steg 2", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_min", label: "min", tag: "steg 2", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_kan", label: "kan", tag: "steg 2", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_kam", label: "kam", tag: "steg 2", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_tak", label: "tak", tag: "steg 2", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_nase", label: "nase", tag: "steg 2", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_vase", label: "vase", tag: "steg 2", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_kake", label: "kake", tag: "steg 2", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_vise", label: "vise", tag: "steg 2", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_ost", label: "ost", tag: "steg 2", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava. NB: o = annan lyd." },
        { id: "o_sint", label: "sint", tag: "steg 2", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_salt", label: "salt", tag: "steg 2", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_stol", label: "stol", tag: "steg 2", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava. NB: o = annan lyd." },
        { id: "o_tre", label: "tre", tag: "steg 2", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_far", label: "far", tag: "steg 3", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_fem", label: "fem", tag: "steg 3", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_fin", label: "fin", tag: "steg 3", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_fot", label: "fot", tag: "steg 3", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava. NB: o = annan lyd." },
        { id: "o_gul", label: "gul", tag: "steg 3", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_gås", label: "gås", tag: "steg 3", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_god", label: "god", tag: "steg 3", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava. NB: o = annan lyd." },
        { id: "o_dag", label: "dag", tag: "steg 3", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_dal", label: "dal", tag: "steg 3", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_due", label: "due", tag: "steg 3", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_uke", label: "uke", tag: "steg 3", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_gate", label: "gate", tag: "steg 3", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_måne", label: "måne", tag: "steg 3", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_sofa", label: "sofa", tag: "steg 3", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava. NB: o = annan lyd." },
        { id: "o_mus", label: "mus", tag: "steg 3", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_sur", label: "sur", tag: "steg 3", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_gris", label: "gris", tag: "steg 3", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_drage", label: "drage", tag: "steg 3", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_bil", label: "bil", tag: "steg 4", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_bok", label: "bok", tag: "steg 4", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava. NB: o = annan lyd." },
        { id: "o_pil", label: "pil", tag: "steg 4", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_pose", label: "pose", tag: "steg 4", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_hus", label: "hus", tag: "steg 4", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_hår", label: "hår", tag: "steg 4", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_hest", label: "hest", tag: "steg 4", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_lys", label: "lys", tag: "steg 4", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_by", label: "by", tag: "steg 4", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_fly", label: "fly", tag: "steg 4", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_øre", label: "øre", tag: "steg 4", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_søt", label: "søt", tag: "steg 4", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_høne", label: "høne", tag: "steg 4", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_pen", label: "pen", tag: "steg 4", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_hale", label: "hale", tag: "steg 4", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_bål", label: "bål", tag: "steg 4", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_jul", label: "jul", tag: "steg 5", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_ja", label: "ja", tag: "steg 5", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_jente", label: "jente", tag: "steg 5", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_hær", label: "hær", tag: "steg 5", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_lære", label: "lære", tag: "steg 5", hint: "Les ordet naturleg og heilt — ikkje lydert, ikkje stava." },
        { id: "o_ring", label: "ring", tag: "steg 6 · ng", hint: "Les ordet naturleg og heilt. «ng» står for éin lyd." },
        { id: "o_ting", label: "ting", tag: "steg 6 · ng", hint: "Les ordet naturleg og heilt. «ng» står for éin lyd." },
        { id: "o_seng", label: "seng", tag: "steg 6 · ng", hint: "Les ordet naturleg og heilt. «ng» står for éin lyd." },
        { id: "o_lang", label: "lang", tag: "steg 6 · ng", hint: "Les ordet naturleg og heilt. «ng» står for éin lyd." },
        { id: "o_tung", label: "tung", tag: "steg 6 · ng", hint: "Les ordet naturleg og heilt. «ng» står for éin lyd." },
        { id: "o_song", label: "song", tag: "steg 6 · ng", hint: "Les ordet naturleg og heilt. «ng» står for éin lyd. O-lyden kan variere med talemålet." },
        { id: "o_gang", label: "gang", tag: "steg 6 · ng", hint: "Les ordet naturleg og heilt. «ng» står for éin lyd." },
        { id: "o_sving", label: "sving", tag: "steg 6 · ng", hint: "Les ordet naturleg og heilt. «ng» står for éin lyd." },
        { id: "o_vinge", label: "vinge", tag: "steg 6 · ng", hint: "Les ordet naturleg og heilt. «ng» står for éin lyd." },
        { id: "o_mange", label: "mange", tag: "steg 6 · ng", hint: "Les ordet naturleg og heilt. «ng» står for éin lyd." },
        { id: "o_tunge", label: "tunge", tag: "steg 6 · ng", hint: "Les ordet naturleg og heilt. «ng» står for éin lyd." },
        { id: "o_konge", label: "konge", tag: "steg 6 · ng", hint: "Les ordet naturleg og heilt. «ng» står for éin lyd." },
      ]
    },
    {
      id: "ros",
      name: "Ros og instruksjonar",
      note: "Rosklippa blir spelte hundrevis av gonger — varier tonefallet. Dei fire oppmuntringane skal vere heilt utan skuffelse i stemma.",
      items: [
        { id: "r_bra", label: "«Bra!»", tag: "ros", hint: "Varier tonefallet — klippet blir spelt hundrevis av gonger." },
        { id: "r_rett", label: "«Rett!»", tag: "ros", hint: "Varier tonefallet — klippet blir spelt hundrevis av gonger." },
        { id: "r_flott", label: "«Flott!»", tag: "ros", hint: "Varier tonefallet — klippet blir spelt hundrevis av gonger." },
        { id: "r_gjort", label: "«Godt gjort!»", tag: "ros", hint: "Varier tonefallet — klippet blir spelt hundrevis av gonger." },
        { id: "r_derja", label: "«Der, ja!»", tag: "ros", hint: "Varier tonefallet — klippet blir spelt hundrevis av gonger." },
        { id: "r_nettopp", label: "«Nettopp!»", tag: "ros", hint: "Varier tonefallet — klippet blir spelt hundrevis av gonger." },
        { id: "r_klarte", label: "«Du klarte det!»", tag: "ros", hint: "Varier tonefallet — klippet blir spelt hundrevis av gonger." },
        { id: "r_flink", label: "«Så flink du er!»", tag: "ros", hint: "Varier tonefallet — klippet blir spelt hundrevis av gonger." },
        { id: "r_prov", label: "«Prøv ein gong til.»", tag: "oppmuntring", hint: "Vennleg og utan skuffelse i stemma." },
        { id: "r_nesten", label: "«Nesten. Høyr ein gong til.»", tag: "oppmuntring", hint: "Vennleg og utan skuffelse i stemma." },
        { id: "r_saman", label: "«Ikkje heilt. Vi tek han saman.»", tag: "oppmuntring", hint: "Vennleg og utan skuffelse i stemma." },
        { id: "r_vanskeleg", label: "«Den var vanskeleg. Sjå her.»", tag: "oppmuntring", hint: "Vennleg og utan skuffelse i stemma." },
        { id: "r_okt", label: "«Økta er ferdig. Godt jobba!»", tag: "avslutning", hint: "Roleg og varm — dette er siste ordet i økta." },
      ]
    }
  ]
};
