/* Shared library integration: real controls in all three tools and an old name picker. */
const path = require('node:path'), assert = require('node:assert/strict');
const { chromium } = require(process.env.VYRDEPIL_PLAYWRIGHT || 'playwright');
const base = process.env.VYRDEPIL_TEST_URL || 'http://127.0.0.1:18191';
let browser;
(async () => {
    browser = await chromium.launch({ headless: true, executablePath: process.env.VYRDEPIL_BROWSER || undefined });
    const context = await browser.newContext({ viewport: { width: 1280, height: 900 } }), errors = [];
    context.on('page', page => page.on('pageerror', e => errors.push(e.message)));
    const page = await context.newPage(); await page.goto(base + '/tevlingstreet/');
    await page.getByRole('button', { name: 'Elevbiblioteket', exact: true }).click();
    await page.getByRole('button', { name: 'Ny elevliste', exact: true }).click();
    await page.getByLabel('Namn på lista eller gruppesettet').fill('QA-klassen');
    await page.getByLabel('Nye elevnamn, eitt per linje').fill('Ada\nAda\nBjørn\nLiv\nKari\nOla');
    await page.getByRole('button', { name: 'Legg til namna', exact: true }).click();
    await page.getByRole('button', { name: 'Lagre i biblioteket', exact: true }).click();
    await page.keyboard.press('Escape');
    await page.goto(base + '/flokkdeilar/');
    await page.locator('#btnElevbibliotek').click();
    await page.getByRole('button', { name: 'Bruk elevlista', exact: true }).click();
    await page.getByText('6 elevar', { exact: true }).waitFor();
    await page.getByRole('link', { name: 'Trekk grupper', exact: true }).click();
    await page.locator('#selectMode').selectOption('groups'); await page.locator('#inputValue').fill('2');
    await page.locator('#btnTrekk').click();
    await page.locator('#btnSaveGroups').click();
    await page.getByLabel('Namn på lista eller gruppesettet').fill('Gymlag');
    await page.getByRole('button', { name: 'Lagre i biblioteket', exact: true }).click();
    await page.goto(base + '/klassekart/');
    await page.locator('#btn-file').click(); await page.locator('#btn-library-open').click();
    await page.getByRole('heading', { name: 'QA-klassen', exact: true }).first().locator('..').getByRole('button', { name: 'Bruk elevlista', exact: true }).click();
    assert.equal(await page.evaluate(() => App.getStudentList().length), 6);
    await page.locator('#btn-library-groups').click();
    await page.getByLabel('Gruppenamn', { exact: true }).fill('Arbeid');
    await page.locator('dialog[open] input[type=checkbox]').nth(0).check();
    await page.locator('dialog[open] input[type=checkbox]').nth(2).check();
    await page.getByRole('button', { name: 'Legg til den valde gruppa', exact: true }).click();
    await page.getByRole('button', { name: 'Namngje og lagre gruppesettet', exact: true }).click();
    await page.getByLabel('Namn på lista eller gruppesettet').fill('Arbeidsgrupper');
    await page.getByRole('button', { name: 'Lagre i biblioteket', exact: true }).click();
    const entries = await page.evaluate(() => VyrdepilElevgrupper.getAll());
    assert.equal(entries.find(e => e.name === 'Gymlag').groups.length, 2);
    assert.equal(entries.find(e => e.name === 'Arbeidsgrupper').groups[0].memberIds.length, 2);
    assert.equal(new Set(entries.find(e => e.name === 'QA-klassen').students.map(s => s.id)).size, 6);
    await page.goto(base + '/tevlingstreet/');
    await page.getByLabel('Kven skal tevle?').selectOption('teams');
    await page.getByRole('button', { name: 'Hent elevar eller grupper', exact: true }).click();
    await page.getByRole('heading', { name: 'Gymlag', exact: true }).locator('..').getByRole('button', { name: 'Bruk gruppene', exact: true }).click();
    assert.equal(await page.locator('.ts-members .ts-member input[aria-label^="Elevnamn"]').count(), 6);
    // A mobile-friendly select moves a pupil between teams.
    const move = page.locator('.ts-member select[aria-label^="Flytt"]').first();
    const options = await move.locator('option').evaluateAll(nodes => nodes.map(o => o.value));
    await move.selectOption(options[1]);
    assert.equal(await page.locator('.ts-members .ts-member input[aria-label^="Elevnamn"]').count(), 6);
    await page.getByRole('button', { name: 'Lag og kontroller kampoppsettet', exact: true }).click();
    await page.getByRole('button', { name: 'Fest oppsettet', exact: true }).click();
    const teamNames = await page.locator('.ts-match-side strong').allTextContents();
    await page.evaluate(() => { const entry = VyrdepilElevgrupper.getAll().find(e => e.name === 'Gymlag'); entry.groups[0].name = 'Endra etter start'; VyrdepilElevgrupper.save(entry); });
    await page.reload(); assert.deepEqual(await page.locator('.ts-match-side strong').allTextContents(), teamNames);
    // The compatible source module returns both equal names and old app sources.
    await page.goto(base + '/tidvis/');
    const sources = await page.evaluate(() => VyrdepilElevlister.kjelder());
    assert.equal(sources.find(e => e.label === 'QA-klassen').names.filter(n => n === 'Ada').length, 2);
    assert(sources.some(e => e.source === 'Flokkdeilar'));
    assert.deepEqual(errors, []);
    await context.close(); await browser.close(); console.log('PASS: bibliotek, Flokkdeilar, Klassekart, lagflytting, kopiar og gamle namneveljarar.');
})().catch(async error => { console.error(error); await browser?.close(); process.exitCode = 1; });
